export enum RolUsuario {
  CLIENTE = 'CLIENTE',
  REPARTIDOR = 'REPARTIDOR',
}

export enum TipoPedido {
  LIBRE = 'LIBRE',
  CATALOGO = 'CATALOGO',
}

export enum EstadoPedido {
  BUSCANDO_REPARTIDOR = 'BUSCANDO_REPARTIDOR',
  ASIGNADO = 'ASIGNADO',
  PRECIO_PENDIENTE = 'PRECIO_PENDIENTE',
  PRECIO_CONFIRMADO = 'PRECIO_CONFIRMADO',
  LISTO_PARA_RETIRAR = 'LISTO_PARA_RETIRAR',
  EN_CAMINO = 'EN_CAMINO',
  ENTREGADO = 'ENTREGADO',
  CANCELADO = 'CANCELADO',
  CANCELADO_PRECIO = 'CANCELADO_PRECIO',
}

export enum EstadoDocumento {
  PENDIENTE = 'PENDIENTE',
  APROBADO = 'APROBADO',
  RECHAZADO = 'RECHAZADO',
}

export enum EstadoRepartidor {
  DISPONIBLE = 'DISPONIBLE',
  NO_DISPONIBLE = 'NO_DISPONIBLE',
  EN_PEDIDO = 'EN_PEDIDO',
}
